### ISSUE TITLE
Implementing best practices for running behind Amazon AWS ELB

### ISSUE THREAD

**Issue by kazuho** [h2o/h2o#395]
To achieve the goal, we need to:
* [x] implement the PROXY protocol (#386)
* [x] implement a way to share secrets used for encrypting SSL session tickets (#400)
* [x] implement a way to share information for ID-based SSL session resumption (#391)

see also: [The sad state of server-side TLS Session Resumption implementations](https://timtaubert.de/blog/2014/11/the-sad-state-of-server-side-tls-session-resumption-implementations/)

**Comment by kazuho** [comment]
For SSL session tickets, at the very minimum, we need to provide a way to set the secret externally.  Implementing automatic roll-over of the secrets (stored either internally or on memcached) is desirable.

We might also consider encrypting the information stored on memcached for ID-based session resumption.

**Comment by kazuho** [comment]
We are now function-complete.  Leftovers are:

* [ ] securely clear sensitive information of resumption cache being passed to/from memcached
* [ ] do not emit `failed to receive response` error when memcached stops running, since it is misleading
 * it should better say that the connection has been closed
