### ISSUE TITLE
mruby-related tasks for 1.7

### ISSUE THREAD

**Issue by kazuho** [h2o/h2o#643]
Task-tracking issue for 1.7:
* [x] implement env["rack.input"] #638
* [x] asynchronous http client #637 #651 
* [x] set MRB_INT64 on 64-bit system #639
* [x] raise error when trying to read `rack.input` already closed #644
* [x] use fiber for calling `#each` to read response from rack app
 * [x] `http_request` should return response progressively using `#each` #645
 * [x] provide `#as_str` in response object #649 (changed to `#json` as part of #651)
 * [x] implement fast-path for rack-app directly passing back the response of `http_request` to core #665
* [x] respect `content-length` header supplied from rack app #664
* [x] add tests for #565 #666
* [ ] separate timeout for http_request?
 * at the moment, the value is fixed to that defined using [`proxy.timeout.io`](https://h2o.examp1e.net/configure/proxy_directives.html#proxy.timeout.io)
* [ ] provide an easy-to-use API to copy the headers passed to `http_request`, as well as set `x-forwarded-for` and `x-forwarded-proto`, via, etc.?
* [x] find a way to handle 399 response returned after async calls #707
* [x] related bug issues: #647 #648 #650 #658 #680 #701

related:
* [ ] support persistent connections in http1client not using the per-host connection pool?

**Comment by kazuho** [comment]
I think we are ready for 1.7.  Remaining tasks should be handled in future releases.
